// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zanzarah_fairy_book;

#nullable disable

namespace Zanzarah_fairy_book.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240629154153_evolve_forms")]
    partial class evolve_forms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Zanzarah_fairy_book.Models.EvolveForm", b =>
                {
                    b.Property<int>("FromId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FromId", "ToId");

                    b.HasIndex("ToId");

                    b.ToTable("EvolveForms");
                });

            modelBuilder.Entity("Zanzarah_fairy_book.Models.Fairy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Element")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvolveItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvolveKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvolveLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpAbility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Special")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fairies");
                });

            modelBuilder.Entity("Zanzarah_fairy_book.Models.EvolveForm", b =>
                {
                    b.HasOne("Zanzarah_fairy_book.Models.Fairy", "From")
                        .WithMany("EvolveToForms")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zanzarah_fairy_book.Models.Fairy", "To")
                        .WithMany("EvolveFromForms")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Zanzarah_fairy_book.Models.Fairy", b =>
                {
                    b.Navigation("EvolveFromForms");

                    b.Navigation("EvolveToForms");
                });
#pragma warning restore 612, 618
        }
    }
}
